version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    container_name: springboot-api
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # se necessário
    restart: always

volumes:
  mongodb_data:
